"""Add notification preferences to User model

Revision ID: 87c9cb439e3c
Revises: 
Create Date: 2024-09-29 18:52:18.855231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '87c9cb439e3c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('price_notifications', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('fvg_notifications', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('oi_notifications', sa.Boolean(), nullable=True))
    op.drop_column('users', 'last_notifications')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_notifications', mysql.JSON(), nullable=True))
    op.drop_column('users', 'oi_notifications')
    op.drop_column('users', 'fvg_notifications')
    op.drop_column('users', 'price_notifications')
    # ### end Alembic commands ###
